//! Build-time validation for the deliberately small Win32 resource catalog.
//!
//! This module uses only the standard library so `build.rs` and unit tests share
//! exactly the same parser and validation rules.

use std::collections::{BTreeSet, HashMap, HashSet};

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct Define {
    pub name: String,
    pub value: usize,
}

pub fn parse_header(source: &str) -> Result<Vec<Define>, String> {
    let mut names = HashSet::new();
    let mut values = HashSet::new();
    let mut defines = Vec::new();
    for (line_number, line) in source.lines().enumerate() {
        let line = line.split("//").next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let words: Vec<_> = line.split_whitespace().collect();
        if words.first() != Some(&"#define") {
            return Err(format!(
                "resource.h:{}: expected `#define NAME INTEGER`",
                line_number + 1
            ));
        }
        if words.len() != 3 || !is_identifier(words[1]) {
            return Err(format!(
                "resource.h:{}: expected `#define NAME INTEGER`",
                line_number + 1
            ));
        }
        let value = words[2].parse::<usize>().map_err(|_| {
            format!(
                "resource.h:{}: ID values must be decimal integers",
                line_number + 1
            )
        })?;
        if !names.insert(words[1]) {
            return Err(format!(
                "resource.h:{}: duplicate ID name `{}`",
                line_number + 1,
                words[1]
            ));
        }
        if !values.insert(value) {
            return Err(format!(
                "resource.h:{}: duplicate ID value {value}",
                line_number + 1
            ));
        }
        defines.push(Define {
            name: words[1].to_owned(),
            value,
        });
    }
    if defines.is_empty() {
        return Err("resource.h defines no IDs".to_owned());
    }
    Ok(defines)
}

pub fn generate_rust(defines: &[Define]) -> String {
    let mut output =
        String::from("// Generated by build.rs from assets/resource.h. Do not edit.\n");
    for define in defines {
        output.push_str(&format!(
            "pub const {}: usize = {};\n",
            define.name, define.value
        ));
    }
    for (name, predicate) in [
        (
            "COMMAND_IDS",
            "ID_FILE_|ID_EDIT_|ID_FORMAT_|ID_VIEW_|ID_HELP_",
        ),
        ("LOCALIZED_STRING_IDS", "IDS_"),
    ] {
        let prefixes: Vec<_> = predicate.trim_end_matches('|').split('|').collect();
        output.push_str(&format!("pub const {name}: &[usize] = &["));
        for define in defines
            .iter()
            .filter(|item| prefixes.iter().any(|prefix| item.name.starts_with(prefix)))
        {
            output.push_str(&format!("{},", define.name));
        }
        output.push_str("];\n");
    }
    output
}

pub fn validate_locale(
    source: &str,
    known_strings: &BTreeSet<String>,
    english: Option<&LocaleShape>,
) -> Result<LocaleShape, String> {
    let strings = parse_stringtable(source)?;
    let actual: BTreeSet<_> = strings.keys().cloned().collect();
    if &actual != known_strings {
        let missing: Vec<_> = known_strings.difference(&actual).cloned().collect();
        let unknown: Vec<_> = actual.difference(known_strings).cloned().collect();
        return Err(format!(
            "localized STRINGTABLE IDs differ; missing={missing:?}, unknown={unknown:?}"
        ));
    }
    let menu = parse_menu_shape(source)?;
    let shape = LocaleShape { strings, menu };
    if let Some(english) = english {
        if shape.menu != english.menu {
            return Err("localized MENU shape differs from English".to_owned());
        }
        for (id, text) in &shape.strings {
            let expected = english.strings.get(id).expect("matching ID sets");
            let expected = placeholders(expected)?;
            let actual = placeholders(text)?;
            if expected != actual {
                return Err(format!("placeholder set for {id} differs from English"));
            }
        }
    } else {
        for text in shape.strings.values() {
            placeholders(text)?;
        }
    }
    Ok(shape)
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct LocaleShape {
    strings: HashMap<String, String>,
    menu: Vec<String>,
}

fn parse_stringtable(source: &str) -> Result<HashMap<String, String>, String> {
    let mut in_table = false;
    let mut result = HashMap::new();
    for (line_number, raw) in source.lines().enumerate() {
        let line = raw.split("//").next().unwrap_or("").trim();
        if line.eq_ignore_ascii_case("STRINGTABLE") {
            in_table = true;
            continue;
        }
        if !in_table || line.eq_ignore_ascii_case("BEGIN") {
            continue;
        }
        if line.eq_ignore_ascii_case("END") {
            in_table = false;
            continue;
        }
        let Some((name, text)) = line.split_once(char::is_whitespace) else {
            continue;
        };
        let name = name.trim();
        let text = text.trim();
        if !name.starts_with("IDS_") || !text.starts_with('"') || !text.ends_with('"') {
            return Err(format!(
                "locale:{}: malformed STRINGTABLE entry",
                line_number + 1
            ));
        }
        if result
            .insert(name.to_owned(), unescape_rc(&text[1..text.len() - 1]))
            .is_some()
        {
            return Err(format!(
                "locale:{}: duplicate STRINGTABLE ID `{name}`",
                line_number + 1
            ));
        }
    }
    Ok(result)
}

fn parse_menu_shape(source: &str) -> Result<Vec<String>, String> {
    let mut menu_started = false;
    let mut depth = 0usize;
    let mut shape = Vec::new();
    for raw in source.lines() {
        let line = raw.split("//").next().unwrap_or("").trim();
        if line.contains(" MENU") && line.starts_with("IDR_") {
            menu_started = true;
            shape.push("MENU".to_owned());
            continue;
        }
        if !menu_started {
            continue;
        }
        if line.eq_ignore_ascii_case("BEGIN") {
            depth += 1;
            shape.push("BEGIN".to_owned());
        } else if line.eq_ignore_ascii_case("END") {
            if depth == 0 {
                return Err("main MENU has an unmatched END".to_owned());
            }
            shape.push("END".to_owned());
            depth -= 1;
            if depth == 0 {
                return Ok(shape);
            }
        } else if line.starts_with("POPUP ") {
            shape.push("POPUP".to_owned());
        } else if line.eq_ignore_ascii_case("MENUITEM SEPARATOR") {
            shape.push("SEPARATOR".to_owned());
        } else if line.starts_with("MENUITEM ") {
            let id = line
                .rsplit_once(',')
                .map(|(_, id)| id.trim())
                .ok_or_else(|| "malformed MENUITEM".to_owned())?;
            if !is_identifier(id) {
                return Err(format!("malformed menu command ID `{id}`"));
            }
            shape.push(format!("COMMAND:{id}"));
        }
    }
    if !menu_started {
        return Err("locale defines no main MENU resource".to_owned());
    }
    Err("main MENU is missing its closing END".to_owned())
}

fn placeholders(text: &str) -> Result<BTreeSet<u32>, String> {
    let mut result = BTreeSet::new();
    let mut chars = text.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch != '%' {
            continue;
        }
        match chars.peek().copied() {
            Some('%') => {
                chars.next();
            }
            Some('1'..='9') => {
                let mut value = String::new();
                while let Some(digit @ '0'..='9') = chars.peek().copied() {
                    value.push(digit);
                    chars.next();
                }
                result.insert(value.parse().expect("digits"));
            }
            _ => return Err(format!("unsupported percent sequence in `{text}`")),
        }
    }
    Ok(result)
}

fn unescape_rc(value: &str) -> String {
    let mut result = String::with_capacity(value.len());
    let mut chars = value.chars().peekable();
    while let Some(character) = chars.next() {
        match character {
            '"' if chars.next_if_eq(&'"').is_some() => result.push('"'),
            '\\' => match chars.next() {
                Some('n') => result.push('\n'),
                Some('t') => result.push('\t'),
                Some('\\') => result.push('\\'),
                Some('"') => result.push('"'),
                Some(other) => {
                    result.push('\\');
                    result.push(other);
                }
                None => result.push('\\'),
            },
            other => result.push(other),
        }
    }
    result
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    matches!(chars.next(), Some('A'..='Z' | 'a'..='z' | '_'))
        && chars.all(|ch| matches!(ch, 'A'..='Z' | 'a'..='z' | '0'..='9' | '_'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_rejects_duplicate_names_and_values() {
        assert!(parse_header("#define ID_A 1\n#define ID_A 2").is_err());
        assert!(parse_header("#define ID_A 1\n#define ID_B 1").is_err());
        assert!(parse_header("#define ID_A not-a-number").is_err());
        assert!(parse_header("#define ID_A 1 extra").is_err());
    }

    #[test]
    fn generated_constants_preserve_header_names_and_categories() {
        let definitions = parse_header("#define ID_FILE_NEW 1\n#define IDS_TITLE 2").unwrap();
        let generated = generate_rust(&definitions);
        assert!(generated.contains("pub const ID_FILE_NEW: usize = 1;"));
        assert!(generated.contains("COMMAND_IDS"));
        assert!(generated.contains("LOCALIZED_STRING_IDS"));
    }

    #[test]
    fn locale_validation_rejects_missing_ids_and_changed_placeholders() {
        let known = BTreeSet::from(["IDS_A".to_owned()]);
        let english = validate_locale("IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %1\"\nEND", &known, None).unwrap();
        assert!(validate_locale("IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %2\"\nEND", &known, Some(&english)).is_err());
        assert!(validate_locale("IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nEND", &known, Some(&english)).is_err());
        assert!(validate_locale("IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_OTHER\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %1\"\nEND", &known, Some(&english)).is_err());
    }

    #[test]
    fn menu_shape_stops_at_the_menu_root_end() {
        let source = "IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Later\"\nEND";
        assert_eq!(
            parse_menu_shape(source).unwrap(),
            ["MENU", "BEGIN", "COMMAND:ID_FILE_NEW", "END"]
        );
    }

    #[test]
    fn rc_unescaping_supports_quotes_tabs_and_line_breaks() {
        assert_eq!(
            unescape_rc(r#"A ""quote""\tline\nnext"#),
            "A \"quote\"\tline\nnext"
        );
    }
}
