//! Build-time validation for the deliberately small Win32 resource catalog.
//!
//! This module uses only the standard library so `build.rs` and unit tests share
//! exactly the same parser and validation rules.

use std::collections::{BTreeSet, HashMap, HashSet};

pub type Language = (u16, u16);

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct Define {
    pub name: String,
    pub value: usize,
}

pub fn parse_header(source: &str) -> Result<Vec<Define>, String> {
    let mut names = HashSet::new();
    let mut values = HashSet::new();
    let mut defines = Vec::new();
    for (line_number, line) in source.lines().enumerate() {
        let line = line.split("//").next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let words: Vec<_> = line.split_whitespace().collect();
        if words.first() != Some(&"#define") {
            return Err(format!(
                "resource.h:{}: expected `#define NAME INTEGER`",
                line_number + 1
            ));
        }
        if words.len() != 3 || !is_identifier(words[1]) {
            return Err(format!(
                "resource.h:{}: expected `#define NAME INTEGER`",
                line_number + 1
            ));
        }
        let value = words[2].parse::<usize>().map_err(|_| {
            format!(
                "resource.h:{}: ID values must be decimal integers",
                line_number + 1
            )
        })?;
        if !(1..=u16::MAX as usize).contains(&value) {
            return Err(format!(
                "resource.h:{}: ID value {value} must be in the range 1..=65535",
                line_number + 1
            ));
        }
        if !names.insert(words[1]) {
            return Err(format!(
                "resource.h:{}: duplicate ID name `{}`",
                line_number + 1,
                words[1]
            ));
        }
        if !values.insert(value) {
            return Err(format!(
                "resource.h:{}: duplicate ID value {value}",
                line_number + 1
            ));
        }
        defines.push(Define {
            name: words[1].to_owned(),
            value,
        });
    }
    if defines.is_empty() {
        return Err("resource.h defines no IDs".to_owned());
    }
    Ok(defines)
}

pub fn generate_rust(defines: &[Define]) -> String {
    let mut output =
        String::from("// Generated by build.rs from assets/resource.h. Do not edit.\n");
    for define in defines {
        output.push_str(&format!(
            "pub const {}: usize = {};\n",
            define.name, define.value
        ));
    }
    for (name, predicate) in [
        (
            "COMMAND_IDS",
            "ID_FILE_|ID_EDIT_|ID_FORMAT_|ID_VIEW_|ID_HELP_",
        ),
        ("LOCALIZED_STRING_IDS", "IDS_"),
    ] {
        let prefixes: Vec<_> = predicate.trim_end_matches('|').split('|').collect();
        output.push_str(&format!("pub const {name}: &[usize] = &["));
        for define in defines
            .iter()
            .filter(|item| prefixes.iter().any(|prefix| item.name.starts_with(prefix)))
        {
            output.push_str(&format!("{},", define.name));
        }
        output.push_str("];\n");
    }
    output
}

pub fn validate_locale(
    source: &str,
    known_strings: &BTreeSet<String>,
    english: Option<&LocaleShape>,
) -> Result<LocaleShape, String> {
    let language = parse_language(source)?;
    if english.is_none() && language != (9, 1) {
        return Err(format!(
            "English (United States) baseline must use `LANGUAGE 9, 1`, found `LANGUAGE {}, {}`",
            language.0, language.1
        ));
    }
    let strings = parse_stringtable(source)?;
    let actual: BTreeSet<_> = strings.keys().cloned().collect();
    if &actual != known_strings {
        let missing: Vec<_> = known_strings.difference(&actual).cloned().collect();
        let unknown: Vec<_> = actual.difference(known_strings).cloned().collect();
        return Err(format!(
            "localized STRINGTABLE IDs differ; missing={missing:?}, unknown={unknown:?}"
        ));
    }
    let menu = parse_menu_shape(source)?;
    let shape = LocaleShape {
        language,
        strings,
        menu,
    };
    if let Some(english) = english {
        if shape.menu != english.menu {
            return Err("localized MENU shape differs from English".to_owned());
        }
        for (id, text) in &shape.strings {
            let expected = english.strings.get(id).expect("matching ID sets");
            let expected = placeholders(expected)?;
            let actual = placeholders(text)?;
            if expected != actual {
                return Err(format!("placeholder set for {id} differs from English"));
            }
        }
    } else {
        for text in shape.strings.values() {
            placeholders(text)?;
        }
    }
    Ok(shape)
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub struct LocaleShape {
    language: Language,
    strings: HashMap<String, String>,
    menu: Vec<String>,
}

impl LocaleShape {
    pub fn language(&self) -> Language {
        self.language
    }
}

pub fn validate_unique_languages<'a>(
    catalogs: impl IntoIterator<Item = (&'a str, Language)>,
) -> Result<(), String> {
    let mut seen = HashMap::new();
    for (catalog, language) in catalogs {
        if let Some(previous) = seen.insert(language, catalog) {
            return Err(format!(
                "duplicate `LANGUAGE {}, {}` in `{previous}` and `{catalog}`",
                language.0, language.1
            ));
        }
    }
    Ok(())
}

fn parse_language(source: &str) -> Result<Language, String> {
    let mut language = None;
    for (line_number, raw) in source.lines().enumerate() {
        let line = raw.split("//").next().unwrap_or("").trim();
        let Some(keyword) = line.split_whitespace().next() else {
            continue;
        };
        if !keyword.eq_ignore_ascii_case("LANGUAGE") {
            continue;
        }
        if language.is_some() {
            return Err(format!(
                "locale:{}: multiple LANGUAGE directives are not supported",
                line_number + 1
            ));
        }
        let arguments = line[keyword.len()..].trim();
        let values = arguments.split(',').map(str::trim).collect::<Vec<_>>();
        if values.len() != 2
            || values
                .iter()
                .any(|value| value.is_empty() || !value.bytes().all(|byte| byte.is_ascii_digit()))
        {
            return Err(format!(
                "locale:{}: expected `LANGUAGE <decimal-primary>, <decimal-sublanguage>`",
                line_number + 1
            ));
        }
        let primary = values[0].parse::<u16>().map_err(|_| {
            format!(
                "locale:{}: LANGUAGE primary value is outside the supported decimal range",
                line_number + 1
            )
        })?;
        let sublanguage = values[1].parse::<u16>().map_err(|_| {
            format!(
                "locale:{}: LANGUAGE sublanguage value is outside the supported decimal range",
                line_number + 1
            )
        })?;
        language = Some((primary, sublanguage));
    }
    language.ok_or_else(|| "locale: missing LANGUAGE directive".to_owned())
}

fn parse_stringtable(source: &str) -> Result<HashMap<String, String>, String> {
    let mut in_table = false;
    let mut result = HashMap::new();
    for (line_number, raw) in source.lines().enumerate() {
        let line = raw.split("//").next().unwrap_or("").trim();
        if line.eq_ignore_ascii_case("STRINGTABLE") {
            in_table = true;
            continue;
        }
        if !in_table || line.eq_ignore_ascii_case("BEGIN") {
            continue;
        }
        if line.eq_ignore_ascii_case("END") {
            in_table = false;
            continue;
        }
        let Some((name, text)) = line.split_once(char::is_whitespace) else {
            continue;
        };
        let name = name.trim();
        let text = text.trim();
        if !name.starts_with("IDS_") || !text.starts_with('"') || !text.ends_with('"') {
            return Err(format!(
                "locale:{}: malformed STRINGTABLE entry",
                line_number + 1
            ));
        }
        let value = unescape_rc(&text[1..text.len() - 1]);
        if value.is_empty() {
            return Err(format!(
                "locale:{}: localized string `{name}` must not be empty",
                line_number + 1
            ));
        }
        if result.insert(name.to_owned(), value).is_some() {
            return Err(format!(
                "locale:{}: duplicate STRINGTABLE ID `{name}`",
                line_number + 1
            ));
        }
    }
    Ok(result)
}

fn parse_menu_shape(source: &str) -> Result<Vec<String>, String> {
    let mut menu_started = false;
    let mut depth = 0usize;
    let mut shape = Vec::new();
    for (line_number, raw) in source.lines().enumerate() {
        let line = raw.split("//").next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let words = line.split_whitespace().collect::<Vec<_>>();
        if words.len() == 2 && words[0].starts_with("IDR_") && words[1].eq_ignore_ascii_case("MENU")
        {
            if words[0] != "IDR_MAIN_MENU" {
                return Err(format!(
                    "locale:{}: expected `IDR_MAIN_MENU MENU`, found `{line}`",
                    line_number + 1
                ));
            }
            menu_started = true;
            shape.push("MENU".to_owned());
            continue;
        }
        if !menu_started {
            continue;
        }
        if line.eq_ignore_ascii_case("BEGIN") {
            depth += 1;
            shape.push("BEGIN".to_owned());
        } else if line.eq_ignore_ascii_case("END") {
            if depth == 0 {
                return Err("main MENU has an unmatched END".to_owned());
            }
            shape.push("END".to_owned());
            depth -= 1;
            if depth == 0 {
                return Ok(shape);
            }
        } else if let Some(label) = line.strip_prefix("POPUP ") {
            if quoted_label_remainder(label).is_none_or(|remainder| !remainder.is_empty()) {
                return Err(format!(
                    "locale:{}: expected `POPUP \"localized label\"`",
                    line_number + 1
                ));
            }
            shape.push("POPUP".to_owned());
        } else if line.eq_ignore_ascii_case("MENUITEM SEPARATOR") {
            shape.push("SEPARATOR".to_owned());
        } else if let Some(item) = line.strip_prefix("MENUITEM ") {
            let remainder = quoted_label_remainder(item).ok_or_else(|| {
                format!(
                    "locale:{}: expected `MENUITEM \"localized label\", ID_COMMAND`",
                    line_number + 1
                )
            })?;
            let id = remainder.strip_prefix(',').map(str::trim).ok_or_else(|| {
                format!(
                    "locale:{}: expected `MENUITEM \"localized label\", ID_COMMAND`",
                    line_number + 1
                )
            })?;
            if id.contains(',') {
                return Err(format!(
                    "locale:{}: trailing MENUITEM flags are unsupported; expected `MENUITEM \"localized label\", ID_COMMAND`",
                    line_number + 1
                ));
            }
            if !is_identifier(id) {
                return Err(format!(
                    "locale:{}: malformed menu command ID `{id}`",
                    line_number + 1
                ));
            }
            shape.push(format!("COMMAND:{id}"));
        } else {
            return Err(format!(
                "locale:{}: unsupported syntax in IDR_MAIN_MENU: `{line}`",
                line_number + 1
            ));
        }
    }
    if !menu_started {
        return Err("locale defines no main MENU resource".to_owned());
    }
    Err("main MENU is missing its closing END".to_owned())
}

fn quoted_label_remainder(value: &str) -> Option<&str> {
    let value = value.strip_prefix('"')?;
    let mut characters = value.char_indices().peekable();
    while let Some((index, character)) = characters.next() {
        if character != '"' {
            continue;
        }
        if characters.peek().is_some_and(|(_, next)| *next == '"') {
            characters.next();
            continue;
        }
        return Some(value[index + 1..].trim());
    }
    None
}

fn placeholders(text: &str) -> Result<BTreeSet<u32>, String> {
    let mut result = BTreeSet::new();
    let mut chars = text.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch != '%' {
            continue;
        }
        match chars.peek().copied() {
            Some('%') => {
                chars.next();
            }
            Some('1'..='9') => {
                let mut value = String::new();
                while let Some(digit @ '0'..='9') = chars.peek().copied() {
                    value.push(digit);
                    chars.next();
                }
                result.insert(value.parse().expect("digits"));
            }
            _ => return Err(format!("unsupported percent sequence in `{text}`")),
        }
    }
    Ok(result)
}

fn unescape_rc(value: &str) -> String {
    let mut result = String::with_capacity(value.len());
    let mut chars = value.chars().peekable();
    while let Some(character) = chars.next() {
        match character {
            '"' if chars.next_if_eq(&'"').is_some() => result.push('"'),
            '\\' => match chars.next() {
                Some('n') => result.push('\n'),
                Some('t') => result.push('\t'),
                Some('\\') => result.push('\\'),
                Some('"') => result.push('"'),
                Some(other) => {
                    result.push('\\');
                    result.push(other);
                }
                None => result.push('\\'),
            },
            other => result.push(other),
        }
    }
    result
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    matches!(chars.next(), Some('A'..='Z' | 'a'..='z' | '_'))
        && chars.all(|ch| matches!(ch, 'A'..='Z' | 'a'..='z' | '0'..='9' | '_'))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_rejects_duplicate_names_and_values() {
        assert!(parse_header("#define ID_A 1\n#define ID_A 2").is_err());
        assert!(parse_header("#define ID_A 1\n#define ID_B 1").is_err());
        assert!(parse_header("#define ID_A not-a-number").is_err());
        assert!(parse_header("#define ID_A 1 extra").is_err());
    }

    #[test]
    fn header_enforces_the_supported_win32_id_range() {
        assert!(parse_header("#define ID_ZERO 0").is_err());
        assert_eq!(
            parse_header("#define ID_MAX 65535").unwrap()[0].value,
            65535
        );
        assert!(parse_header("#define ID_TOO_LARGE 65536").is_err());
    }

    #[test]
    fn generated_constants_preserve_header_names_and_categories() {
        let definitions = parse_header("#define ID_FILE_NEW 1\n#define IDS_TITLE 2").unwrap();
        let generated = generate_rust(&definitions);
        assert!(generated.contains("pub const ID_FILE_NEW: usize = 1;"));
        assert!(generated.contains("COMMAND_IDS"));
        assert!(generated.contains("LOCALIZED_STRING_IDS"));
    }

    #[test]
    fn locale_validation_rejects_missing_ids_and_changed_placeholders() {
        let known = BTreeSet::from(["IDS_A".to_owned()]);
        let english = validate_locale("LANGUAGE 9, 1\nIDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %1\"\nEND", &known, None).unwrap();
        assert!(validate_locale("LANGUAGE 12, 1\nIDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %2\"\nEND", &known, Some(&english)).is_err());
        assert!(validate_locale("LANGUAGE 12, 1\nIDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nEND\nSTRINGTABLE\nBEGIN\nEND", &known, Some(&english)).is_err());
        assert!(validate_locale("LANGUAGE 12, 1\nIDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_OTHER\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"Value %1\"\nEND", &known, Some(&english)).is_err());
    }

    #[test]
    fn menu_shape_tracks_nested_popups_separators_and_ordered_commands() {
        let source = "IDR_MAIN_MENU MENU\nBEGIN\nPOPUP \"&File\"\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW\nMENUITEM SEPARATOR\nPOPUP \"Nested\"\nBEGIN\nMENUITEM \"B\", ID_FILE_OPEN\nEND\nEND\nEND";
        assert_eq!(
            parse_menu_shape(source).unwrap(),
            [
                "MENU",
                "BEGIN",
                "POPUP",
                "BEGIN",
                "COMMAND:ID_FILE_NEW",
                "SEPARATOR",
                "POPUP",
                "BEGIN",
                "COMMAND:ID_FILE_OPEN",
                "END",
                "END",
                "END"
            ]
        );
    }

    #[test]
    fn menu_rejects_wrong_identity_and_trailing_flags() {
        assert!(parse_menu_shape("IDR_OTHER MENU\nBEGIN\nEND").is_err());
        let error = parse_menu_shape(
            "IDR_MAIN_MENU MENU\nBEGIN\nMENUITEM \"A\", ID_FILE_NEW, CHECKED, GRAYED\nEND",
        )
        .unwrap_err();
        assert!(error.contains("trailing MENUITEM flags"));
    }

    #[test]
    fn locale_validation_rejects_empty_strings() {
        let known = BTreeSet::from(["IDS_A".to_owned()]);
        let error = validate_locale(
            "LANGUAGE 9, 1\nIDR_MAIN_MENU MENU\nBEGIN\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"\"\nEND",
            &known,
            None,
        )
        .unwrap_err();
        assert!(error.contains("must not be empty"));
    }

    #[test]
    fn locale_validation_requires_supported_language_directives() {
        let known = BTreeSet::from(["IDS_A".to_owned()]);
        let catalog = |language: &str| {
            format!(
                "{language}\nIDR_MAIN_MENU MENU\nBEGIN\nEND\nSTRINGTABLE\nBEGIN\nIDS_A \"A\"\nEND"
            )
        };
        assert!(validate_locale(&catalog(""), &known, None).is_err());
        assert!(validate_locale(&catalog("LANGUAGE nine, 1"), &known, None).is_err());
        assert!(validate_locale(&catalog("LANGUAGE 9, 1\nLANGUAGE 9, 1"), &known, None).is_err());
        assert!(validate_locale(&catalog("LANGUAGE 9, 2"), &known, None).is_err());
        assert_eq!(
            validate_locale(&catalog("LANGUAGE 9, 1"), &known, None)
                .unwrap()
                .language(),
            (9, 1)
        );
    }

    #[test]
    fn duplicate_locale_languages_are_rejected() {
        let error = validate_unique_languages([("en-US.rc", (9, 1)), ("copied-locale.rc", (9, 1))])
            .unwrap_err();
        assert!(error.contains("duplicate `LANGUAGE 9, 1`"));
    }

    #[test]
    fn rc_unescaping_supports_quotes_tabs_and_line_breaks() {
        assert_eq!(
            unescape_rc(r#"A ""quote""\tline\nnext"#),
            "A \"quote\"\tline\nnext"
        );
    }
}
